package iti.jets.misk.entities;// Generated Apr 10, 2025, 10:36:31 PM by Hibernate Tools 6.0.2.Final


import jakarta.persistence.*;

/**
 * Orderitems generated by hbm2java
 */
@Entity
@Table(name="orderitems"
    ,catalog="misk"
)
public class Orderitems  implements java.io.Serializable {


     private OrderitemsId id;
     private Order order;
     private Product product;
     private int quantity;

    public Orderitems() {
    }

    public Orderitems(OrderitemsId id, Order order, Product product, int quantity) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public OrderitemsId getId() {
        return this.id;
    }
    
    public void setId(OrderitemsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false, insertable=false, updatable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


